/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AdsRouteImport } from './routes/ads'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as InterestsRouteImport } from './routes/interests'
import { Route as LiveRouteImport } from './routes/live'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ReelsRouteImport } from './routes/reels'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as StyleguideRouteImport } from './routes/styleguide'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as LiveStreamIdRouteImport } from './routes/live.$streamId'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'
import { Route as SystemIndexRouteImport } from './routes/system.index'
import { Route as SystemDashboardRouteImport } from './routes/system.dashboard'
import { Route as TagTagRouteImport } from './routes/tag.$tag'
import { Route as SystemDashboardIndexRouteImport } from './routes/system.dashboard.index'
import { Route as SystemDashboardAccountsRouteImport } from './routes/system.dashboard.accounts'
import { Route as SystemDashboardActivityRouteImport } from './routes/system.dashboard.activity'
import { Route as SystemDashboardAuditRouteImport } from './routes/system.dashboard.audit'
import { Route as SystemDashboardCampaignsRouteImport } from './routes/system.dashboard.campaigns'
import { Route as SystemDashboardGrowthRouteImport } from './routes/system.dashboard.growth'
import { Route as SystemDashboardLiveRouteImport } from './routes/system.dashboard.live'
import { Route as SystemDashboardModerationRouteImport } from './routes/system.dashboard.moderation'
import { Route as SystemDashboardPaymentsRouteImport } from './routes/system.dashboard.payments'
import { Route as SystemDashboardRewardsRouteImport } from './routes/system.dashboard.rewards'
import { Route as SystemDashboardSettingsRouteImport } from './routes/system.dashboard.settings'
import { Route as SystemDashboardStaffRouteImport } from './routes/system.dashboard.staff'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsRoute = AdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const InterestsRoute = InterestsRouteImport.update({
  id: '/interests',
  path: '/interests',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelsRoute = ReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleguideRoute = StyleguideRouteImport.update({
  id: '/styleguide',
  path: '/styleguide',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveStreamIdRoute = LiveStreamIdRouteImport.update({
  id: '/$streamId',
  path: '/$streamId',
  getParentRoute: () => LiveRoute,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemIndexRoute = SystemIndexRouteImport.update({
  id: '/system/',
  path: '/system/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemDashboardRoute = SystemDashboardRouteImport.update({
  id: '/system/dashboard',
  path: '/system/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TagTagRoute = TagTagRouteImport.update({
  id: '/tag/$tag',
  path: '/tag/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemDashboardIndexRoute = SystemDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SystemDashboardRoute,
} as any)
const SystemDashboardAccountsRoute = SystemDashboardAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => SystemDashboardRoute,
} as any)
const SystemDashboardActivityRoute = SystemDashboardActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => SystemDashboardRoute,
} as any)
const SystemDashboardAuditRoute = SystemDashboardAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => SystemDashboardRoute,
} as any)
const SystemDashboardCampaignsRoute =
  SystemDashboardCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => SystemDashboardRoute,
  } as any)
const SystemDashboardGrowthRoute = SystemDashboardGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => SystemDashboardRoute,
} as any)
const SystemDashboardLiveRoute = SystemDashboardLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => SystemDashboardRoute,
} as any)
const SystemDashboardModerationRoute =
  SystemDashboardModerationRouteImport.update({
    id: '/moderation',
    path: '/moderation',
    getParentRoute: () => SystemDashboardRoute,
  } as any)
const SystemDashboardPaymentsRoute = SystemDashboardPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => SystemDashboardRoute,
} as any)
const SystemDashboardRewardsRoute = SystemDashboardRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => SystemDashboardRoute,
} as any)
const SystemDashboardSettingsRoute = SystemDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SystemDashboardRoute,
} as any)
const SystemDashboardStaffRoute = SystemDashboardStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => SystemDashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/ads': typeof AdsRoute
  '/bookmarks': typeof BookmarksRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/interests': typeof InterestsRoute
  '/live': typeof LiveRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/reels': typeof ReelsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/studio': typeof StudioRoute
  '/styleguide': typeof StyleguideRoute
  '/verify': typeof VerifyRoute
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/live/$streamId': typeof LiveStreamIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/system/dashboard': typeof SystemDashboardRouteWithChildren
  '/tag/$tag': typeof TagTagRoute
  '/system/': typeof SystemIndexRoute
  '/system/dashboard/accounts': typeof SystemDashboardAccountsRoute
  '/system/dashboard/activity': typeof SystemDashboardActivityRoute
  '/system/dashboard/audit': typeof SystemDashboardAuditRoute
  '/system/dashboard/campaigns': typeof SystemDashboardCampaignsRoute
  '/system/dashboard/growth': typeof SystemDashboardGrowthRoute
  '/system/dashboard/live': typeof SystemDashboardLiveRoute
  '/system/dashboard/moderation': typeof SystemDashboardModerationRoute
  '/system/dashboard/payments': typeof SystemDashboardPaymentsRoute
  '/system/dashboard/rewards': typeof SystemDashboardRewardsRoute
  '/system/dashboard/settings': typeof SystemDashboardSettingsRoute
  '/system/dashboard/staff': typeof SystemDashboardStaffRoute
  '/system/dashboard/': typeof SystemDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/ads': typeof AdsRoute
  '/bookmarks': typeof BookmarksRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/interests': typeof InterestsRoute
  '/live': typeof LiveRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/reels': typeof ReelsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/studio': typeof StudioRoute
  '/styleguide': typeof StyleguideRoute
  '/verify': typeof VerifyRoute
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/live/$streamId': typeof LiveStreamIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/tag/$tag': typeof TagTagRoute
  '/system': typeof SystemIndexRoute
  '/system/dashboard/accounts': typeof SystemDashboardAccountsRoute
  '/system/dashboard/activity': typeof SystemDashboardActivityRoute
  '/system/dashboard/audit': typeof SystemDashboardAuditRoute
  '/system/dashboard/campaigns': typeof SystemDashboardCampaignsRoute
  '/system/dashboard/growth': typeof SystemDashboardGrowthRoute
  '/system/dashboard/live': typeof SystemDashboardLiveRoute
  '/system/dashboard/moderation': typeof SystemDashboardModerationRoute
  '/system/dashboard/payments': typeof SystemDashboardPaymentsRoute
  '/system/dashboard/rewards': typeof SystemDashboardRewardsRoute
  '/system/dashboard/settings': typeof SystemDashboardSettingsRoute
  '/system/dashboard/staff': typeof SystemDashboardStaffRoute
  '/system/dashboard': typeof SystemDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/ads': typeof AdsRoute
  '/bookmarks': typeof BookmarksRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/interests': typeof InterestsRoute
  '/live': typeof LiveRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/reels': typeof ReelsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/studio': typeof StudioRoute
  '/styleguide': typeof StyleguideRoute
  '/verify': typeof VerifyRoute
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/live/$streamId': typeof LiveStreamIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/system/dashboard': typeof SystemDashboardRouteWithChildren
  '/tag/$tag': typeof TagTagRoute
  '/system/': typeof SystemIndexRoute
  '/system/dashboard/accounts': typeof SystemDashboardAccountsRoute
  '/system/dashboard/activity': typeof SystemDashboardActivityRoute
  '/system/dashboard/audit': typeof SystemDashboardAuditRoute
  '/system/dashboard/campaigns': typeof SystemDashboardCampaignsRoute
  '/system/dashboard/growth': typeof SystemDashboardGrowthRoute
  '/system/dashboard/live': typeof SystemDashboardLiveRoute
  '/system/dashboard/moderation': typeof SystemDashboardModerationRoute
  '/system/dashboard/payments': typeof SystemDashboardPaymentsRoute
  '/system/dashboard/rewards': typeof SystemDashboardRewardsRoute
  '/system/dashboard/settings': typeof SystemDashboardSettingsRoute
  '/system/dashboard/staff': typeof SystemDashboardStaffRoute
  '/system/dashboard/': typeof SystemDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/ads'
    | '/bookmarks'
    | '/explore'
    | '/forgot-password'
    | '/interests'
    | '/live'
    | '/login'
    | '/notifications'
    | '/reels'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/studio'
    | '/styleguide'
    | '/verify'
    | '/wallet'
    | '/welcome'
    | '/live/$streamId'
    | '/profile/$username'
    | '/system/dashboard'
    | '/tag/$tag'
    | '/system/'
    | '/system/dashboard/accounts'
    | '/system/dashboard/activity'
    | '/system/dashboard/audit'
    | '/system/dashboard/campaigns'
    | '/system/dashboard/growth'
    | '/system/dashboard/live'
    | '/system/dashboard/moderation'
    | '/system/dashboard/payments'
    | '/system/dashboard/rewards'
    | '/system/dashboard/settings'
    | '/system/dashboard/staff'
    | '/system/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/ads'
    | '/bookmarks'
    | '/explore'
    | '/forgot-password'
    | '/interests'
    | '/live'
    | '/login'
    | '/notifications'
    | '/reels'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/studio'
    | '/styleguide'
    | '/verify'
    | '/wallet'
    | '/welcome'
    | '/live/$streamId'
    | '/profile/$username'
    | '/tag/$tag'
    | '/system'
    | '/system/dashboard/accounts'
    | '/system/dashboard/activity'
    | '/system/dashboard/audit'
    | '/system/dashboard/campaigns'
    | '/system/dashboard/growth'
    | '/system/dashboard/live'
    | '/system/dashboard/moderation'
    | '/system/dashboard/payments'
    | '/system/dashboard/rewards'
    | '/system/dashboard/settings'
    | '/system/dashboard/staff'
    | '/system/dashboard'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/ads'
    | '/bookmarks'
    | '/explore'
    | '/forgot-password'
    | '/interests'
    | '/live'
    | '/login'
    | '/notifications'
    | '/reels'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/studio'
    | '/styleguide'
    | '/verify'
    | '/wallet'
    | '/welcome'
    | '/live/$streamId'
    | '/profile/$username'
    | '/system/dashboard'
    | '/tag/$tag'
    | '/system/'
    | '/system/dashboard/accounts'
    | '/system/dashboard/activity'
    | '/system/dashboard/audit'
    | '/system/dashboard/campaigns'
    | '/system/dashboard/growth'
    | '/system/dashboard/live'
    | '/system/dashboard/moderation'
    | '/system/dashboard/payments'
    | '/system/dashboard/rewards'
    | '/system/dashboard/settings'
    | '/system/dashboard/staff'
    | '/system/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AdsRoute: typeof AdsRoute
  BookmarksRoute: typeof BookmarksRoute
  ExploreRoute: typeof ExploreRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InterestsRoute: typeof InterestsRoute
  LiveRoute: typeof LiveRouteWithChildren
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ReelsRoute: typeof ReelsRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  StudioRoute: typeof StudioRoute
  StyleguideRoute: typeof StyleguideRoute
  VerifyRoute: typeof VerifyRoute
  WalletRoute: typeof WalletRoute
  WelcomeRoute: typeof WelcomeRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  SystemDashboardRoute: typeof SystemDashboardRouteWithChildren
  TagTagRoute: typeof TagTagRoute
  SystemIndexRoute: typeof SystemIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads': {
      id: '/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interests': {
      id: '/interests'
      path: '/interests'
      fullPath: '/interests'
      preLoaderRoute: typeof InterestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reels': {
      id: '/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof ReelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styleguide': {
      id: '/styleguide'
      path: '/styleguide'
      fullPath: '/styleguide'
      preLoaderRoute: typeof StyleguideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$streamId': {
      id: '/live/$streamId'
      path: '/$streamId'
      fullPath: '/live/$streamId'
      preLoaderRoute: typeof LiveStreamIdRouteImport
      parentRoute: typeof LiveRoute
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/': {
      id: '/system/'
      path: '/system'
      fullPath: '/system/'
      preLoaderRoute: typeof SystemIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/dashboard': {
      id: '/system/dashboard'
      path: '/system/dashboard'
      fullPath: '/system/dashboard'
      preLoaderRoute: typeof SystemDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag/$tag': {
      id: '/tag/$tag'
      path: '/tag/$tag'
      fullPath: '/tag/$tag'
      preLoaderRoute: typeof TagTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/dashboard/': {
      id: '/system/dashboard/'
      path: '/'
      fullPath: '/system/dashboard/'
      preLoaderRoute: typeof SystemDashboardIndexRouteImport
      parentRoute: typeof SystemDashboardRoute
    }
    '/system/dashboard/accounts': {
      id: '/system/dashboard/accounts'
      path: '/accounts'
      fullPath: '/system/dashboard/accounts'
      preLoaderRoute: typeof SystemDashboardAccountsRouteImport
      parentRoute: typeof SystemDashboardRoute
    }
    '/system/dashboard/activity': {
      id: '/system/dashboard/activity'
      path: '/activity'
      fullPath: '/system/dashboard/activity'
      preLoaderRoute: typeof SystemDashboardActivityRouteImport
      parentRoute: typeof SystemDashboardRoute
    }
    '/system/dashboard/audit': {
      id: '/system/dashboard/audit'
      path: '/audit'
      fullPath: '/system/dashboard/audit'
      preLoaderRoute: typeof SystemDashboardAuditRouteImport
      parentRoute: typeof SystemDashboardRoute
    }
    '/system/dashboard/campaigns': {
      id: '/system/dashboard/campaigns'
      path: '/campaigns'
      fullPath: '/system/dashboard/campaigns'
      preLoaderRoute: typeof SystemDashboardCampaignsRouteImport
      parentRoute: typeof SystemDashboardRoute
    }
    '/system/dashboard/growth': {
      id: '/system/dashboard/growth'
      path: '/growth'
      fullPath: '/system/dashboard/growth'
      preLoaderRoute: typeof SystemDashboardGrowthRouteImport
      parentRoute: typeof SystemDashboardRoute
    }
    '/system/dashboard/live': {
      id: '/system/dashboard/live'
      path: '/live'
      fullPath: '/system/dashboard/live'
      preLoaderRoute: typeof SystemDashboardLiveRouteImport
      parentRoute: typeof SystemDashboardRoute
    }
    '/system/dashboard/moderation': {
      id: '/system/dashboard/moderation'
      path: '/moderation'
      fullPath: '/system/dashboard/moderation'
      preLoaderRoute: typeof SystemDashboardModerationRouteImport
      parentRoute: typeof SystemDashboardRoute
    }
    '/system/dashboard/payments': {
      id: '/system/dashboard/payments'
      path: '/payments'
      fullPath: '/system/dashboard/payments'
      preLoaderRoute: typeof SystemDashboardPaymentsRouteImport
      parentRoute: typeof SystemDashboardRoute
    }
    '/system/dashboard/rewards': {
      id: '/system/dashboard/rewards'
      path: '/rewards'
      fullPath: '/system/dashboard/rewards'
      preLoaderRoute: typeof SystemDashboardRewardsRouteImport
      parentRoute: typeof SystemDashboardRoute
    }
    '/system/dashboard/settings': {
      id: '/system/dashboard/settings'
      path: '/settings'
      fullPath: '/system/dashboard/settings'
      preLoaderRoute: typeof SystemDashboardSettingsRouteImport
      parentRoute: typeof SystemDashboardRoute
    }
    '/system/dashboard/staff': {
      id: '/system/dashboard/staff'
      path: '/staff'
      fullPath: '/system/dashboard/staff'
      preLoaderRoute: typeof SystemDashboardStaffRouteImport
      parentRoute: typeof SystemDashboardRoute
    }
  }
}

interface LiveRouteChildren {
  LiveStreamIdRoute: typeof LiveStreamIdRoute
}

const LiveRouteChildren: LiveRouteChildren = {
  LiveStreamIdRoute: LiveStreamIdRoute,
}

const LiveRouteWithChildren = LiveRoute._addFileChildren(LiveRouteChildren)

interface SystemDashboardRouteChildren {
  SystemDashboardAccountsRoute: typeof SystemDashboardAccountsRoute
  SystemDashboardActivityRoute: typeof SystemDashboardActivityRoute
  SystemDashboardAuditRoute: typeof SystemDashboardAuditRoute
  SystemDashboardCampaignsRoute: typeof SystemDashboardCampaignsRoute
  SystemDashboardGrowthRoute: typeof SystemDashboardGrowthRoute
  SystemDashboardLiveRoute: typeof SystemDashboardLiveRoute
  SystemDashboardModerationRoute: typeof SystemDashboardModerationRoute
  SystemDashboardPaymentsRoute: typeof SystemDashboardPaymentsRoute
  SystemDashboardRewardsRoute: typeof SystemDashboardRewardsRoute
  SystemDashboardSettingsRoute: typeof SystemDashboardSettingsRoute
  SystemDashboardStaffRoute: typeof SystemDashboardStaffRoute
  SystemDashboardIndexRoute: typeof SystemDashboardIndexRoute
}

const SystemDashboardRouteChildren: SystemDashboardRouteChildren = {
  SystemDashboardAccountsRoute: SystemDashboardAccountsRoute,
  SystemDashboardActivityRoute: SystemDashboardActivityRoute,
  SystemDashboardAuditRoute: SystemDashboardAuditRoute,
  SystemDashboardCampaignsRoute: SystemDashboardCampaignsRoute,
  SystemDashboardGrowthRoute: SystemDashboardGrowthRoute,
  SystemDashboardLiveRoute: SystemDashboardLiveRoute,
  SystemDashboardModerationRoute: SystemDashboardModerationRoute,
  SystemDashboardPaymentsRoute: SystemDashboardPaymentsRoute,
  SystemDashboardRewardsRoute: SystemDashboardRewardsRoute,
  SystemDashboardSettingsRoute: SystemDashboardSettingsRoute,
  SystemDashboardStaffRoute: SystemDashboardStaffRoute,
  SystemDashboardIndexRoute: SystemDashboardIndexRoute,
}

const SystemDashboardRouteWithChildren = SystemDashboardRoute._addFileChildren(
  SystemDashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdsRoute: AdsRoute,
  BookmarksRoute: BookmarksRoute,
  ExploreRoute: ExploreRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InterestsRoute: InterestsRoute,
  LiveRoute: LiveRouteWithChildren,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ReelsRoute: ReelsRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  StudioRoute: StudioRoute,
  StyleguideRoute: StyleguideRoute,
  VerifyRoute: VerifyRoute,
  WalletRoute: WalletRoute,
  WelcomeRoute: WelcomeRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  SystemDashboardRoute: SystemDashboardRouteWithChildren,
  TagTagRoute: TagTagRoute,
  SystemIndexRoute: SystemIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
